namespace IDisposableGenerator;

internal sealed class VisualBasicGeneratedCodeWriter : IGeneratedCodeWriter
{
    public List<(string file, StringBuilder code)> ToCodeStrings(SourceProductionContext ctx, ReadOnlyCollection<WorkItem> workItems)
    {
        List<(string file, StringBuilder code)> result = [];
        StringBuilder sourceBuilder = new("' <autogenerated/>");
        _ = sourceBuilder.Append(@"
Imports System
");
        foreach (var workItem in workItems)
        {
            ToVisualBasicCodeString(workItem, ref sourceBuilder);
        }

        result.Add(("Disposables.g.vb", sourceBuilder));
        return result;
    }

    private static void ToVisualBasicCodeString(WorkItem workItem, ref StringBuilder builder)
    {
        if (!string.IsNullOrEmpty(workItem.Namespace))
        {
            _ = builder.Append($@"
Namespace {workItem.Namespace}
");
        }

        foreach (var classItem in workItem.Classes)
        {
            var code = ToVisualBasicCodeString(classItem);
            if (string.IsNullOrEmpty(workItem.Namespace))
            {
                code = WorkItem.ReduceIndentation(code);
            }

            _ = builder.Append(code);
        }

        if (!string.IsNullOrEmpty(workItem.Namespace))
        {
            _ = builder.Append(@"End Namespace
");
        }
    }

    private static string ToVisualBasicCodeString(ClassItems classItem)
    {
        var result = new StringBuilder();
        _ = result.Append($@"
    {(classItem.Accessibility == Accessibility.Public ? "Public" : "Friend")} Partial Class {classItem.Name}{GetInterfaceImplementations(classItem)}
        Private isDisposed As Boolean
");
        if (classItem.Owns.Count is not 0)
        {
            _ = result.Append(classItem.Stream ? @"
        Friend ReadOnly Property KeepOpen As Boolean
" : @"
        Friend Property IsOwned As Boolean
");
        }

        WriteDisposeImplementation(classItem, false, ref result);
        if (classItem.IsAsyncDisposable)
        {
            WriteDisposeImplementation(classItem, true, ref result);
        }

        if (!classItem.WithoutThrowIfDisposed)
        {
            _ = result.Append($$"""

                                Friend Sub ThrowIfDisposed()
                                    If Me.isDisposed Then
                                        Throw New ObjectDisposedException(NameOf({{classItem.Name}}))
                                    End If
                                End Sub

                        """);
        }

        _ = result.Append("""
                        End Class

                    """);
        return result.ToString();
    }

    private static void WriteDisposeImplementation(ClassItems classItem, bool isAsync, ref StringBuilder result)
    {
        _ = result.Append($@"
        {(!classItem.BaseIsDisposable || (isAsync && !classItem.BaseIsAsyncDisposable) ? $@"''' <summary>
        ''' Cleans up the resources used by <see cref=""{classItem.Name}""/>.
        ''' </summary>
        Public Sub Dispose() Implements IDisposable.Dispose
            Me.Dispose(True)
            GC.SuppressFinalize(Me)
        End Sub

        Private" : @"''' <inheritdoc/>
        Protected Overrides")} Sub Dispose(ByVal disposing As Boolean)
            If Not Me.isDisposed AndAlso disposing Then
");
        if (classItem.Methods.Count is not 0)
        {
            foreach (var methodItem in classItem.Methods)
            {
                _ = result.Append($@"                Me.{methodItem}()
");
            }
        }

        if (classItem.Owns.Count is not 0)
        {
            _ = result.Append($@"                If {(classItem.Stream ? "Not Me.KeepOpen" : "Me.IsOwned")} Then
");
            foreach (var ownedItem in classItem.Owns)
            {
                // automatically set to null after Dispose().
                _ = result.Append($@"                    Me.{ownedItem.Symbol.Name}?.Dispose()
{(!ClassItems.IsReadOnlyField(ownedItem.Symbol) ? $@"                    Me.{ownedItem.Symbol.Name} = Nothing
" : string.Empty)}");
            }

            _ = result.Append(@"                End If
");
        }

        if (classItem.Fields.Count is not 0)
        {
            foreach (var fieldItem in classItem.Fields)
            {
                // automatically set to null after Dispose().
                _ = result.Append($@"                Me.{fieldItem.Symbol.Name}?.Dispose()
{(!ClassItems.IsReadOnlyField(fieldItem.Symbol) ? $@"                Me.{fieldItem.Symbol.Name} = Nothing
" : string.Empty)}");
            }
        }

        if (classItem.SetNull.Count is not 0)
        {
            foreach (var nullItem in classItem.SetNull)
            {
                _ = result.Append($@"                Me.{nullItem} = Nothing
");
            }
        }

        _ = result.Append(@"                Me.isDisposed = True
            End If
");
        if (classItem.BaseIsDisposable || classItem.BaseIsAsyncDisposable)
        {
            _ = result.Append(@"
            ' On disposable bases call MyBase.Dispose(disposing)!!!
            MyBase.Dispose(disposing)
");
        }

        _ = result.Append("""
                            End Sub

                    """);
    }

    private static string GetInterfaceImplementations(ClassItems classItem)
        => (!classItem.BaseIsDisposable, classItem.IsAsyncDisposable && !classItem.BaseIsAsyncDisposable) switch
        {
            (false, false) => string.Empty,
            (true, false) => @"
        Implements IDisposable
",
            // When IAsyncDisposable is implemented, IDisposable must be implemented as well which is as if they were both true.
            (true, true) or (false, true) => @"
        Implements IDisposable
        Implements IAsyncDisposable
",
        };
}
