namespace IDisposableGenerator;

internal sealed class CSharpGeneratedCodeWriter(LanguageVersion languageVersion) : IGeneratedCodeWriter
{
    internal LanguageVersion LanguageVersion { get; set; } = languageVersion;
    internal const LanguageVersion MinimumLanguageVersion = LanguageVersion.CSharp12;

    public List<(string file, StringBuilder code)> ToCodeStrings(SourceProductionContext ctx, ReadOnlyCollection<WorkItem> workItems)
    {
        List<(string file, StringBuilder code)> result = [];
        if (this.LanguageVersion < MinimumLanguageVersion)
        {
            ctx.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    id: "IDISPGEN001",
                    title: "Unsupported C# language version",
                    messageFormat: "The C# language version {0} is not supported as anything older than 'net8.0' has reached end-of-life. Please use C# {1} or higher.",
                    category: "IDisposableGenerator",
                    DiagnosticSeverity.Error,
                    isEnabledByDefault: true),
                null,
                this.LanguageVersion.ToDisplayString(),
                MinimumLanguageVersion.ToDisplayString()));
            return result;
        }

        foreach (var workItem in workItems)
        {
            var sourceBuilder = ToCSharp12CodeString(workItem);
            result.Add((
                $@"Disposables{(
                    workItems.Count > 1
                        ? $".{workItems.IndexOf(workItem)}" :
                        string.Empty)}.g.cs",
                sourceBuilder));
        }
        return result;
    }

    private static StringBuilder ToCSharp12CodeString(WorkItem workItem)
    {
        var result = new StringBuilder("// <autogenerated/>");
        _ = result.Append($@"
{(!string.IsNullOrEmpty(workItem.Namespace) ? $@"namespace {workItem.Namespace};
" : string.Empty)}");
        foreach (var classItem in workItem.Classes)
        {
            ToCSharp12CodeString(classItem, ref result);
        }

        return result;
    }

    private static void ToCSharp12CodeString(ClassItems classItem, ref StringBuilder builder)
    {
        _ = builder.Append($@"
{(classItem.Accessibility == Accessibility.Public ? "public" : "internal")} partial class {classItem.Name}{GetInterfaceImplementations(classItem)}
{{
    private bool isDisposed;
");
        if (classItem.Owns.Count is not 0)
        {
            _ = builder.Append(classItem.Stream ? @"
    internal bool KeepOpen { get; }
" : @"
    internal bool IsOwned { get; set; }
");
        }

        // write normal IDisposable implementation first.
        WriteDisposeImplementation(classItem, false, ref builder);

        // now write IAsyncDisposable implementation if it is requested.
        if (classItem.IsAsyncDisposable || classItem.BaseIsAsyncDisposable)
        {
            WriteDisposeImplementation(classItem, true, ref builder);
        }

        if (!classItem.WithoutThrowIfDisposed)
        {
            _ = builder.Append($@"
    internal void ThrowIfDisposed()
    {{
        if (this.isDisposed)
        {{
            throw new ObjectDisposedException(nameof({classItem.Name}));
        }}
    }}
");
        }

        _ = builder.Append(@"}
");
    }

    private static void WriteDisposeImplementation(ClassItems classItem, bool isAsync, ref StringBuilder builder)
    {
        var methodsignature = isAsync ? "async ValueTask DisposeAsync" : "void Dispose";
        var methodSignatureCore = isAsync ? $"{methodsignature}Core" : methodsignature;
        var methodName = isAsync ? "DisposeAsyncCore" : "Dispose";
        var potentialAwait = isAsync ? "await " : string.Empty;
        var configureAwait = isAsync ? ".ConfigureAwait(false)" : string.Empty;
        _ = builder.Append($@"
    {(!classItem.BaseIsDisposable || (isAsync && !classItem.BaseIsAsyncDisposable) ? $@"/// <summary>
    /// Cleans up the resources used by <see cref=""{classItem.Name}""/>.
    /// </summary>
    public {methodsignature}()
    {{
        {potentialAwait}this.{(methodName == "DisposeAsyncCore" ? $"{methodName}(){configureAwait}" : $"{methodName}(true)")};
        GC.SuppressFinalize(this);
    }}

    protected virtual" : @"/// <inheritdoc/>
    protected override")} {(methodSignatureCore.EndsWith("Core") ? $"{methodSignatureCore}()" : $"{methodSignatureCore}(bool disposing)")}
    {{
{(isAsync ? string.Empty : @"        if (!this.isDisposed && disposing)
        {
")}");
        if (classItem.Methods.Count is not 0)
        {
            foreach (var methodItem in classItem.Methods)
            {
                _ = builder.Append($@"            this.{methodItem}();
");
            }
        }

        if (classItem.Owns.Count is not 0)
        {
            _ = builder.Append(isAsync ? $@"        if ({(classItem.Stream ? "!this.KeepOpen" : "this.IsOwned")})
        {{
" : $@"            if ({(classItem.Stream ? "!this.KeepOpen" : "this.IsOwned")})
            {{
");
            foreach (var (Symbol, IsAsyncDisposable) in classItem.Owns)
            {
                // automatically set to null after Dispose().
                _ = builder.Append($@"                {potentialAwait}this.{Symbol.Name}?.{(isAsync && IsAsyncDisposable && (classItem.IsAsyncDisposable || classItem.BaseIsAsyncDisposable) ? "DisposeAsync" : "Dispose")}(){configureAwait};
{(!ClassItems.IsReadOnlyField(Symbol) ? $@"                this.{Symbol.Name} = null;
" : string.Empty)}");
            }

            _ = builder.Append(@"            }
");
        }

        if (classItem.Fields.Count is not 0)
        {
            foreach (var (Symbol, IsAsyncDisposable) in classItem.Fields)
            {
                // automatically set to null after Dispose().
                _ = builder.Append(isAsync ? $@"        {potentialAwait}this.{Symbol.Name}?.{(isAsync && IsAsyncDisposable && (classItem.IsAsyncDisposable || classItem.BaseIsAsyncDisposable) ? "DisposeAsync" : "Dispose")}(){configureAwait};
{(!ClassItems.IsReadOnlyField(Symbol) ? $@"        this.{Symbol.Name} = null;
" : string.Empty)}" : $@"            {potentialAwait}this.{Symbol.Name}?.Dispose();
{(!ClassItems.IsReadOnlyField(Symbol) ? $@"            this.{Symbol.Name} = null;
" : string.Empty)}");
            }
        }

        if (classItem.SetNull.Count is not 0)
        {
            foreach (var nullItem in classItem.SetNull)
            {
                _ = builder.Append(isAsync ? $@"        this.{nullItem} = null;
" : $@"            this.{nullItem} = null;
");
            }
        }

        _ = builder.Append(isAsync ? @"        this.isDisposed = true;
" : @"            this.isDisposed = true;
        }
");
        if (classItem.BaseIsDisposable || classItem.BaseIsAsyncDisposable)
        {
            _ = builder.Append($@"
        // On disposable bases call base.{(methodName == "DisposeAsyncCore" ? $"DisposeAsync()" : $"{methodName}(disposing)")}!!!
        {potentialAwait}base.{(methodName == "DisposeAsyncCore" ? $"DisposeAsync(){configureAwait}" : $"{methodName}(disposing)")};
");
        }

        _ = builder.Append("""
                        }

                    """);
    }

    private static string GetInterfaceImplementations(ClassItems classItem)
        => (!classItem.BaseIsDisposable, classItem.IsAsyncDisposable && !classItem.BaseIsAsyncDisposable) switch
        {
            (false, false) => string.Empty,
            (true, false) => " : IDisposable",
            // When IAsyncDisposable is implemented, IDisposable must be implemented as well which is as if they were both true.
            (true, true) or (false, true) => " : IDisposable, IAsyncDisposable",
        };
}
