namespace IDisposableGenerator;

using System.Collections.ObjectModel;
using System.Text;

internal sealed class CSharpGeneratedCodeWriter(LanguageVersion languageVersion) : IGeneratedCodeWriter
{
    internal LanguageVersion LanguageVersion { get; set; } = languageVersion;

    public List<(string file, StringBuilder code)> ToCodeStrings(ReadOnlyCollection<WorkItem> workItems)
    {
        List<(string file, StringBuilder code)> result = [];
        if (this.LanguageVersion > LanguageVersion.CSharp9)
        {
            foreach (var workItem in workItems)
            {
                var sourceBuilder = ToCSharp10CodeString(workItem);
                result.Add((
                    $@"Disposables{(
                        workItems.Count > 1
                            ? $".{workItems.IndexOf(workItem)}" :
                            string.Empty)}.g.cs",
                    sourceBuilder));
            }
        }
        else
        {
            var sourceBuilder = new StringBuilder("// <autogenerated/>");
            foreach (var workItem in workItems)
            {
                ToCSharp9CodeString(workItem, ref sourceBuilder);
            }
            result.Add(("Disposables.g.cs", sourceBuilder));
        }
        return result;
    }

    private static void ToCSharp9CodeString(WorkItem workItem, ref StringBuilder builder)
    {
        _ = builder.Append($@"
{(!string.IsNullOrEmpty(workItem.Namespace) ? $@"namespace {workItem.Namespace}
{{
    " : string.Empty)}using global::System;
");
        foreach (var classItem in workItem.Classes)
        {
            var code = ToCSharp9CodeString(classItem);
            if (string.IsNullOrEmpty(workItem.Namespace))
            {
                code = WorkItem.ReduceIndentation(code);
            }

            _ = builder.Append(code);
        }

        if (!string.IsNullOrEmpty(workItem.Namespace))
        {
            _ = builder.Append(@"}
");
        }
    }

    private static string ToCSharp9CodeString(ClassItems classItem)
    {
        var result = new StringBuilder();
        _ = result.Append($@"
    {(classItem.Accessibility == Accessibility.Public ? "public" : "internal")} partial class {classItem.Name}{GetInterfaceImplementations(classItem)}
    {{
        private bool isDisposed;
");
        if (classItem.Owns.Count is not 0)
        {
            _ = result.Append(classItem.Stream ? @"
        internal bool KeepOpen { get; }
" : @"
        internal bool IsOwned { get; set; }
");
        }

        _ = result.Append($@"
        {(!classItem.Stream ? $@"/// <summary>
        /// Cleans up the resources used by <see cref=""{classItem.Name}""/>.
        /// </summary>
        public void Dispose()
        {{
            this.Dispose(true);
            GC.SuppressFinalize(this);
        }}

        private" : @"/// <inheritdoc/>
        protected override")} void Dispose(bool disposing)
        {{
            if (!this.isDisposed && disposing)
            {{
");
        if (classItem.Methods.Count is not 0)
        {
            foreach (var methodItem in classItem.Methods)
            {
                _ = result.Append($@"                this.{methodItem}();
");
            }
        }

        if (classItem.Owns.Count is not 0)
        {
            _ = result.Append($@"                if ({(classItem.Stream ? "!this.KeepOpen" : "this.IsOwned")})
                {{
");
            foreach (var ownedItem in classItem.Owns)
            {
                // automatically set to null after Dispose().
                _ = result.Append($@"                    this.{ownedItem.Name}?.Dispose();
{(!ClassItems.IsReadOnlyField(ownedItem) ? $@"                    this.{ownedItem.Name} = null;
" : string.Empty)}");
            }

            _ = result.Append(@"                }
");
        }

        if (classItem.Fields.Count is not 0)
        {
            foreach (var fieldItem in classItem.Fields)
            {
                // automatically set to null after Dispose().
                _ = result.Append($@"                this.{fieldItem.Name}?.Dispose();
{(!ClassItems.IsReadOnlyField(fieldItem) ? $@"                this.{fieldItem.Name} = null;
" : string.Empty)}");
            }
        }

        if (classItem.SetNull.Count is not 0)
        {
            foreach (var nullItem in classItem.SetNull)
            {
                _ = result.Append($@"                this.{nullItem} = null;
");
            }
        }

        _ = result.Append(@"                this.isDisposed = true;
            }
");
        if (classItem.Stream)
        {
            _ = result.Append(@"
            // On Streams call base.Dispose(disposing)!!!
            base.Dispose(disposing);
");
        }

        _ = result.Append(@"        }
");
        if (!classItem.WithoutThrowIfDisposed)
        {
            _ = result.Append($@"
        internal void ThrowIfDisposed()
        {{
            if (this.isDisposed)
            {{
                throw new ObjectDisposedException(nameof({classItem.Name}));
            }}
        }}
");
        }

        _ = result.Append(@"    }
");

        return result.ToString();
    }

    private static StringBuilder ToCSharp10CodeString(WorkItem workItem)
    {
        var result = new StringBuilder("// <autogenerated/>");
        _ = result.Append($@"
{(!string.IsNullOrEmpty(workItem.Namespace) ? $@"namespace {workItem.Namespace};
" : string.Empty)}");
        foreach (var classItem in workItem.Classes)
        {
            ToCSharp10CodeString(classItem, ref result);
        }

        return result;
    }

    private static void ToCSharp10CodeString(ClassItems classItem, ref StringBuilder builder)
    {
        _ = builder.Append($@"
{(classItem.Accessibility == Accessibility.Public ? "public" : "internal")} partial class {classItem.Name}{GetInterfaceImplementations(classItem)}
{{
    private bool isDisposed;
");
        if (classItem.Owns.Count is not 0)
        {
            _ = builder.Append(classItem.Stream ? @"
    internal bool KeepOpen { get; }
" : @"
    internal bool IsOwned { get; set; }
");
        }

        _ = builder.Append($@"
    {(!classItem.Stream ? $@"/// <summary>
    /// Cleans up the resources used by <see cref=""{classItem.Name}""/>.
    /// </summary>
    public void Dispose()
    {{
        this.Dispose(true);
        GC.SuppressFinalize(this);
    }}

    private" : @"/// <inheritdoc/>
    protected override")} void Dispose(bool disposing)
    {{
        if (!this.isDisposed && disposing)
        {{
");
        if (classItem.Methods.Count is not 0)
        {
            foreach (var methodItem in classItem.Methods)
            {
                _ = builder.Append($@"            this.{methodItem}();
");
            }
        }

        if (classItem.Owns.Count is not 0)
        {
            _ = builder.Append($@"            if ({(classItem.Stream ? "!this.KeepOpen" : "this.IsOwned")})
            {{
");
            foreach (var ownedItem in classItem.Owns)
            {
                // automatically set to null after Dispose().
                _ = builder.Append($@"                this.{ownedItem.Name}?.Dispose();
{(!ClassItems.IsReadOnlyField(ownedItem) ? $@"                this.{ownedItem.Name} = null;
" : string.Empty)}");
            }

            _ = builder.Append(@"            }
");
        }

        if (classItem.Fields.Count is not 0)
        {
            foreach (var fieldItem in classItem.Fields)
            {
                // automatically set to null after Dispose().
                _ = builder.Append($@"            this.{fieldItem.Name}?.Dispose();
{(!ClassItems.IsReadOnlyField(fieldItem) ? $@"            this.{fieldItem.Name} = null;
" : string.Empty)}");
            }
        }

        if (classItem.SetNull.Count is not 0)
        {
            foreach (var nullItem in classItem.SetNull)
            {
                _ = builder.Append($@"            this.{nullItem} = null;
");
            }
        }

        _ = builder.Append(@"            this.isDisposed = true;
        }
");
        if (classItem.Stream)
        {
            _ = builder.Append(@"
        // On Streams call base.Dispose(disposing)!!!
        base.Dispose(disposing);
");
        }

        _ = builder.Append("""
                        }

                    """);

        if (!classItem.WithoutThrowIfDisposed)
        {
            _ = builder.Append($@"
    internal void ThrowIfDisposed()
    {{
        if (this.isDisposed)
        {{
            throw new ObjectDisposedException(nameof({classItem.Name}));
        }}
    }}
");
        }

        _ = builder.Append(@"}
");
    }

    private static string GetInterfaceImplementations(ClassItems classItem)
        => classItem.Stream switch
        {
            false => " : IDisposable",
            true => "",
        };
}
