namespace IDisposableGenerator;

internal sealed class CSharpGeneratedCodeWriter(LanguageVersion languageVersion) : IGeneratedCodeWriter
{
    internal LanguageVersion LanguageVersion { get; set; } = languageVersion;
    internal const LanguageVersion MinimumLanguageVersion = LanguageVersion.CSharp12;

    public List<(string file, StringBuilder code)> ToCodeStrings(SourceProductionContext ctx, ReadOnlyCollection<WorkItem> workItems)
    {
        List<(string file, StringBuilder code)> result = [];
        if (this.LanguageVersion < MinimumLanguageVersion)
        {
            ctx.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    id: "IDISPGEN001",
                    title: "Unsupported C# language version",
                    messageFormat: "The C# language version {0} is not supported as anything older than 'net8.0' has reached end-of-life. Please use C# {1} or higher.",
                    category: "IDisposableGenerator",
                    DiagnosticSeverity.Error,
                    isEnabledByDefault: true),
                null,
                this.LanguageVersion.ToDisplayString(),
                MinimumLanguageVersion.ToDisplayString()));
            return result;
        }

        foreach (var workItem in workItems)
        {
            var sourceBuilder = ToCSharp12CodeString(workItem);
            result.Add((
                $@"Disposables{(
                    workItems.Count > 1
                        ? $".{workItems.IndexOf(workItem)}" :
                        string.Empty)}.g.cs",
                sourceBuilder));
        }
        return result;
    }

    private static StringBuilder ToCSharp12CodeString(WorkItem workItem)
    {
        var result = new StringBuilder("// <autogenerated/>");
        _ = result.Append($@"
{(!string.IsNullOrEmpty(workItem.Namespace) ? $@"namespace {workItem.Namespace};
" : string.Empty)}");
        foreach (var classItem in workItem.Classes)
        {
            ToCSharp12CodeString(classItem, ref result);
        }

        return result;
    }

    private static void ToCSharp12CodeString(ClassItems classItem, ref StringBuilder builder)
    {
        _ = builder.Append($@"
{(classItem.Accessibility == Accessibility.Public ? "public" : "internal")} partial class {classItem.Name}{GetInterfaceImplementations(classItem)}
{{
    private bool isDisposed;
");
        if (classItem.Owns.Count is not 0)
        {
            _ = builder.Append(classItem.Stream ? @"
    internal bool KeepOpen { get; }
" : @"
    internal bool IsOwned { get; set; }
");
        }

        _ = builder.Append($@"
    {(!classItem.Stream ? $@"/// <summary>
    /// Cleans up the resources used by <see cref=""{classItem.Name}""/>.
    /// </summary>
    public void Dispose()
    {{
        this.Dispose(true);
        GC.SuppressFinalize(this);
    }}

    private" : @"/// <inheritdoc/>
    protected override")} void Dispose(bool disposing)
    {{
        if (!this.isDisposed && disposing)
        {{
");
        if (classItem.Methods.Count is not 0)
        {
            foreach (var methodItem in classItem.Methods)
            {
                _ = builder.Append($@"            this.{methodItem}();
");
            }
        }

        if (classItem.Owns.Count is not 0)
        {
            _ = builder.Append($@"            if ({(classItem.Stream ? "!this.KeepOpen" : "this.IsOwned")})
            {{
");
            foreach (var ownedItem in classItem.Owns)
            {
                // automatically set to null after Dispose().
                _ = builder.Append($@"                this.{ownedItem.Name}?.Dispose();
{(!ClassItems.IsReadOnlyField(ownedItem) ? $@"                this.{ownedItem.Name} = null;
" : string.Empty)}");
            }

            _ = builder.Append(@"            }
");
        }

        if (classItem.Fields.Count is not 0)
        {
            foreach (var fieldItem in classItem.Fields)
            {
                // automatically set to null after Dispose().
                _ = builder.Append($@"            this.{fieldItem.Name}?.Dispose();
{(!ClassItems.IsReadOnlyField(fieldItem) ? $@"            this.{fieldItem.Name} = null;
" : string.Empty)}");
            }
        }

        if (classItem.SetNull.Count is not 0)
        {
            foreach (var nullItem in classItem.SetNull)
            {
                _ = builder.Append($@"            this.{nullItem} = null;
");
            }
        }

        _ = builder.Append(@"            this.isDisposed = true;
        }
");
        if (classItem.Stream)
        {
            _ = builder.Append(@"
        // On Streams call base.Dispose(disposing)!!!
        base.Dispose(disposing);
");
        }

        _ = builder.Append("""
                        }

                    """);

        if (!classItem.WithoutThrowIfDisposed)
        {
            _ = builder.Append($@"
    internal void ThrowIfDisposed()
    {{
        if (this.isDisposed)
        {{
            throw new ObjectDisposedException(nameof({classItem.Name}));
        }}
    }}
");
        }

        _ = builder.Append(@"}
");
    }

    private static string GetInterfaceImplementations(ClassItems classItem)
        => classItem.Stream switch
        {
            false => " : IDisposable",
            true => "",
        };
}
