name: .NET Core (build)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@main
    - name: Install latest .NET 10 SDK
      uses: Elskom/setup-latest-dotnet@main
      with:
        SDK_VERSION: '10.0.201'
        RUNTIME_VERSIONS: ''

    - name: Restore, Build, test, and pack
      uses: Elskom/build-dotnet@main
      with:
        TEST: true
        ADDITIONAL_TEST_ARGS: ' --coverlet --coverlet-output-format opencover --results-directory ./tests'
