name: .NET Core (build & publish release)

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    steps:
    - uses: actions/checkout@main
    - name: Install latest .NET 8 SDK
      uses: Elskom/setup-latest-dotnet@main
      with:
        SDK_VERSION: '8.0.200'
        RUNTIME_VERSIONS: ''

    - name: Restore, Build, test, pack, and push
      uses: Elskom/build-dotnet@main
      with:
        TEST: true
        PUSH: true
